# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TreeLeafTechnologies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TreeLeafTechnologies
  pod 'ObjectMapper'
  pod 'Alamofire'

  target 'TreeLeafTechnologiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TreeLeafTechnologiesUITests' do
    # Pods for testing
  end

end
